---

- name: ensure repositories are enabled
  get_url:
    url: "{{ reposrvurl + item + '.repo' }}"
    dest: /etc/yum.repos.d/{{ item }}.repo
    mode: 0644
    owner: root
    group: root
  with_items: "{{ repositories }} "

