---

- name: ensure yum-config-manager is installed
  yum:
    name: yum-utils
    state: present

- name: ensure all repositories are disbaled
  cmd: yum-config-manager --disable "*"
  when: repo_reset == true 
   
- name: ensure repositories are enabled
  get_url:
    url: "{{ reposrvurl + item + '.repo' }}"
    dest: /etc/yum.repos.d/{{ item }}.repo
    mode: 0644
    owner: root
    group: root
  with_items: "{{ repositories }} "

